name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-27"



[vars]
DATABASE_URL="prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjhiM2ZmZmEtMzIzZS00MDlmLWFiNTgtNjMzNWRjMzVhMzU0IiwidGVuYW50X2lkIjoiOGFiM2NmMWU5MWI4NTU5NWYwMDZlMGJkOTEyM2YzMzI2MmQzZDEwNzNhMTgyMGRjNDkwOWI2YWY0ZDhiY2UwNCIsImludGVybmFsX3NlY3JldCI6ImFkOTVlMjY2LTE4NGYtNGE3Ni04M2E3LTE4Mjc1MTQ1MTk1YiJ9.QWjp4FqM7nv50UPucjVwhSofBZXHwtvtoZ_0Xr2KlTM"
JWT_SECRET = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOWIyMDY0YTctOGQwMC00OWQ0LTkwYTUtODhmZTEwMGZhODVhIiwidGVuYW50X2lkIjoiZmYwM2E0Mjc5NThjZDgxZGRmNjg2MWFiZWUwNzM5OGY3ZTlhOWRhY2Q4MGY1NTYwZjk5ZTk2YTVhZDc3YmI2NyIsImludGVybmFsX3NlY3JldCI6ImFhODdjMTQxLWViZjYtNGRjZS1iM2M3LThhN2M3NWJmN2U2ZCJ9.3c24n57NsSMyh_gEB6QlLQHuTL-8uYHpozlXfdBAAkU"